In [ ]:
import string
import numpy as np
import pandas as pd
def read_file(file_path):
    with open(file_path,'r') as file:
        text=file.read()
    return text


def remove_punctuation(text):
    translator=str.maketrans('','',string.punctuation)
    cleaned_text=text.translate(translator)
    words=cleaned_text.split()
    return words



def generate_k_shingles(words,k):
    k_shingles=[''.join(words[i:i+k]) for i in range(len(words)-k+1)]
    return k_shingles

k=5
file_path1='/content/Backyard cricket.txt'
text1=read_file(file_path1)
words1=remove_punctuation(text1)
shingles1=generate_k_shingles(words1,k)


file_path2='/content/Cricket.txt'
text2=read_file(file_path2)
words2=remove_punctuation(text2)
shingles2=generate_k_shingles(words2,k)

file_path3='/content/Baseball.txt'
text3=read_file(file_path3)
words3=remove_punctuation(text3)
shingles3=generate_k_shingles(words3,k)

all_shingles=shingles1+shingles2+shingles3



# Step 1: Combine all shingles and find unique shingles
unique_shingles = list(set(all_shingles))
print(len(unique_shingles))
# Step 2: Initialize an empty incidence matrix
incidence_matrix = np.zeros((len(unique_shingles), 3))

# Step 3: Populate the incidence matrix
for i, shingle in enumerate(unique_shingles):
    if shingle in shingles1:
        incidence_matrix[i, 0] = 1  # Document 1
    if shingle in shingles2:
        incidence_matrix[i, 1] = 1  # Document 2
    if shingle in shingles3:
        incidence_matrix[i, 2] = 1  # Document 3

# Step 4: Create a DataFrame for better visualization (optional)
incidence_df = pd.DataFrame(incidence_matrix, index=unique_shingles, columns=["Document 1", "Document 2", "Document 3"])
incidence_df.insert(0,"Row",range(0,len(unique_shingles)))
# Print the incidence matrix
print(incidence_df)



353
                                   Row  Document 1  Document 2  Document 3
scoringonerunforeach                 0         0.0         1.0         0.0
Baseballisabatandballsport           1         0.0         0.0         1.0
onafieldatthe                        2         0.0         1.0         0.0
withabatTheobjective                 3         0.0         0.0         1.0
beachcricketcorridorcricketgarden    4         1.0         0.0         0.0
...                                ...         ...         ...         ...
aroundfourbasestoscore             348         0.0         0.0         1.0
subcontinentandboxcricketin        349         1.0         0.0         0.0
withthebatandthen                  350         0.0         1.0         0.0
holdingbatswithoneplayer           351         0.0         1.0         0.0
torunthebaseshaving                352         0.0         0.0         1.0

[353 rows x 4 columns]


In [ ]:
#apply Hash Function
incidence_df['h1'] = (incidence_df['Row']+1) % 1000
incidence_df['h2'] = (2 * incidence_df['Row']+5) % 1000

incidence_df = incidence_df.sort_values(by=['h1','h2'])

print(incidence_df)

                                   Row  Document 1  Document 2  Document 3  \
scoringonerunforeach                 0         0.0         1.0         0.0   
Baseballisabatandballsport           1         0.0         0.0         1.0   
onafieldatthe                        2         0.0         1.0         0.0   
withabatTheobjective                 3         0.0         0.0         1.0   
beachcricketcorridorcricketgarden    4         1.0         0.0         0.0   
...                                ...         ...         ...         ...   
aroundfourbasestoscore             348         0.0         0.0         1.0   
subcontinentandboxcricketin        349         1.0         0.0         0.0   
withthebatandthen                  350         0.0         1.0         0.0   
holdingbatswithoneplayer           351         0.0         1.0         0.0   
torunthebaseshaving                352         0.0         0.0         1.0   

                                    h1   h2  
scoringonerunfore

In [ ]:
num_hashes = 2
num_docs = 3
signature_matrix = np.full((num_hashes, num_docs), np.inf)
print(signature_matrix)

for i in range(len(unique_shingles)):
    if incidence_df.iloc[i, 1] == 1:  # Document 1
        signature_matrix[0, 0] = min(signature_matrix[0, 0], incidence_df.iloc[i]['h1'])
        signature_matrix[1, 0] = min(signature_matrix[1, 0], incidence_df.iloc[i]['h2'])
    if incidence_df.iloc[i, 2] == 1:  # Document 2
        signature_matrix[0, 1] = min(signature_matrix[0, 1], incidence_df.iloc[i]['h1'])
        signature_matrix[1, 1] = min(signature_matrix[1, 1], incidence_df.iloc[i]['h2'])
    if incidence_df.iloc[i, 3] == 1:  # Document 3
        signature_matrix[0, 2] = min(signature_matrix[0, 2], incidence_df.iloc[i]['h1'])
        signature_matrix[1, 2] = min(signature_matrix[1, 2], incidence_df.iloc[i]['h2'])
print(signature_matrix)

signature_df = pd.DataFrame(signature_matrix, index=['h1', 'h2'], columns=["Document 1", "Document 2", "Document 3"])
print("\nsignature_matrix :\n")
print(signature_df)

[[inf inf inf]
 [inf inf inf]]
[[ 5.  1.  2.]
 [13.  5.  7.]]

signature_matrix :

    Document 1  Document 2  Document 3
h1         5.0         1.0         2.0
h2        13.0         5.0         7.0


In [1]:

import numpy as np

# Define the input matrix
matrix = np.array([
    (1, 0, 0, 1, 0),  # Set 1
    (0, 0, 1, 0, 0),  # Set 2
    (0, 1, 0, 1, 1),  # Set 3
    (1, 0, 1, 1, 0)   # Set 4
])

# Define the hash functions
def h1(x):
    return (x + 1) % 5

def h2(x):
    return (3 * x + 1) % 5

def h3(x):
    return (4 * x + 1) % 5

# List of hash functions
hash_functions = [h1, h2, h3]

# Initialize the signature matrix with infinity
num_hashes = len(hash_functions)
num_sets, num_elements = matrix.shape
signature_matrix = np.full((num_hashes, num_sets), np.inf)

# Compute the MinHash signatures
for i in range(num_elements):
    if any(matrix[:, i]):  # If the column has a '1'
        for h in range(num_hashes):
            hash_value = hash_functions[h](i)
            for s in range(num_sets):
                if matrix[s, i] == 1:
                    signature_matrix[h, s] = min(signature_matrix[h, s], hash_value)

# Print the signature matrix
print("MinHash Signature Matrix:")
print(signature_matrix)

MinHash Signature Matrix:
[[1. 3. 0. 1.]
 [0. 2. 0. 0.]
 [1. 4. 0. 1.]]


In [ ]:
import pandas as pd
import numpy as np
import random
# with open("1.txt", "r") as file:
#   doc1 = file.read()
# print(doc1)
# with open("2.txt", "r") as file:
#   doc2 = file.read()
# print(doc2)
# Example documents
doc1 = "Data Science and Big Data Analytics"
doc2 = "Big Data and Data Science"
doc3 = "Machine Learning and AI are transforming industries"
doc4 = "Artificial Intelligence in Healthcare"
kval =3
shingle1 = shinglewithoutsepr(doc1, kval)
shingle2 = shinglewithoutsepr(doc2, kval)
shingle3 = shinglewithoutsepr(doc3, kval)
shingle4 = shinglewithoutsepr(doc4, kval)
all_shingles = list(set(shingle1 + shingle2+shingle3+shingle4))
print("Shingle 1:", shingle1)
print("Shingle 2:", shingle2)
print("Shingle 3:", shingle3)
print("Shingle 4:", shingle4)
print("All shingles:", all_shingles)
df = pd.DataFrame(columns=["Shingle", "doc1", "doc2","doc3","doc4"])
df["Shingle"] = all_shingles
df.fillna(0, inplace=True)
for i in range(len(shingle1)):
    df.loc[df["Shingle"] == shingle1[i], "doc1"] = 1
for i in range(len(shingle2)):
    df.loc[df["Shingle"] == shingle2[i], "doc2"] = 1
for i in range(len(shingle3)):
    df.loc[df["Shingle"] == shingle3[i], "doc3"] = 1
for i in range(len(shingle4)):
    df.loc[df["Shingle"] == shingle4[i], "doc4"] = 1
df["Hash1"] = df.index.map(lambda x: (17 * int(x) + 11) % len(df))
df["Hash2"] = df.index.map(lambda x: (7 * int(x) + 11) % len(df))
print(len(df))
print(df)

Shingle 1: ['Dat', 'ata', 'ta ', 'a S', ' Sc', 'Sci', 'cie', 'ien', 'enc', 'nce', 'ce ', 'e a', ' an', 'and', 'nd ', 'd B', ' Bi', 'Big', 'ig ', 'g D', ' Da', 'Dat', 'ata', 'ta ', 'a A', ' An', 'Ana', 'nal', 'aly', 'lyt', 'yti', 'tic', 'ics']
Shingle 2: ['Big', 'ig ', 'g D', ' Da', 'Dat', 'ata', 'ta ', 'a a', ' an', 'and', 'nd ', 'd D', ' Da', 'Dat', 'ata', 'ta ', 'a S', ' Sc', 'Sci', 'cie', 'ien', 'enc', 'nce']
Shingle 3: ['Mac', 'ach', 'chi', 'hin', 'ine', 'ne ', 'e L', ' Le', 'Lea', 'ear', 'arn', 'rni', 'nin', 'ing', 'ng ', 'g a', ' an', 'and', 'nd ', 'd A', ' AI', 'AI ', 'I a', ' ar', 'are', 're ', 'e t', ' tr', 'tra', 'ran', 'ans', 'nsf', 'sfo', 'for', 'orm', 'rmi', 'min', 'ing', 'ng ', 'g i', ' in', 'ind', 'ndu', 'dus', 'ust', 'str', 'tri', 'rie', 'ies']
Shingle 4: ['Art', 'rti', 'tif', 'ifi', 'fic', 'ici', 'cia', 'ial', 'al ', 'l I', ' In', 'Int', 'nte', 'tel', 'ell', 'lli', 'lig', 'ige', 'gen', 'enc', 'nce', 'ce ', 'e i', ' in', 'in ', 'n H', ' He', 'Hea', 'eal', 'alt', 'lth', 

In [ ]:
sig = np.full((2,4), np.inf)
for index, row in df.iterrows():
   if row["doc1"] == 1:
       sig[0, 0] = min(sig[0, 0], row["Hash1"])
       sig[1, 0] = min(sig[1, 0], row["Hash2"])
   if row["doc2"] == 1:
       sig[0, 1] = min(sig[0, 1], row["Hash1"])
       sig[1, 1] = min(sig[1, 1], row["Hash2"])
   if row["doc3"] == 1:
       sig[0, 2] = min(sig[0, 2], row["Hash1"])
       sig[1, 2] = min(sig[1, 2], row["Hash2"])
   if row["doc4"] == 1:
       sig[0, 3] = min(sig[0, 3], row["Hash1"])
       sig[1, 3] = min(sig[1, 3], row["Hash2"])
print("Signature matrix =\n",sig)

Signature matrix =
 [[0. 0. 3. 1.]
 [0. 6. 1. 3.]]
